export const SHOP_BRANDS = [
  'Rolex',
  'Omega',
  'Cartier',
  'Tudor',
  'IWC',
  'Breitling',
  'TAG Heuer',
  'Hublot',
  'Grand Seiko',
  'Tissot',
  'Hamilton',
  'Longines',
  'Seiko',
  'Citizen',
  'Orient',
  'Timex',
];

export const VALUATION_BRANDS = [
  'A. Lange & Söhne',
  'Accurist',
  'Alpina',
  'Audemars Piguet',
  'Baume & Mercier',
  'Bell & Ross',
  'Blancpain',
  'Breguet',
  'Breitling',
  'Bulova',
  'Cartier',
  'Casio',
  'Certina',
  'Chopard',
  'Citizen',
  'Corum',
  'Doxa',
  'Fossil',
  'Frederique Constant',
  'G-Shock',
  'Girard-Perregaux',
  'Grand Seiko',
  'Hamilton',
  'Hublot',
  'IWC',
  'Jaeger-LeCoultre',
  'Junghans',
  'Longines',
  'Maurice Lacroix',
  'Michael Kors',
  'Montblanc',
  'Mondaine',
  'NOMOS Glashütte',
  'Omega',
  'Oris',
  'Orient',
  'Panerai',
  'Patek Philippe',
  'Rado',
  'Raymond Weil',
  'Richard Mille',
  'Rolex',
  'Rotary',
  'Seiko',
  'Sinn',
  'Skagen',
  'Swatch',
  'TAG Heuer',
  'Timex',
  'Tissot',
  'Tudor',
  'Vacheron Constantin',
  'Victorinox',
  'Zenith',
  'Other / Unsure',
];
